version: '3.8'

services:
  chat_app:
    image: iuryanadao/chat_app
    build: .
    stdin_open: true
    tty: true
    container_name: chat_app
    env_file:
      - ./.env.development
    volumes:
      - ./:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    network_mode: host

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat_app_database
      POSTGRES_USER: chat_app_user
      POSTGRES_PASSWORD: 123456789
    network_mode: host
